"""The Linux server installs from a hash-pinned lock (OPS-9).

Pure file checks against ``requirements-linux-py314.lock``,
``pyproject.toml``, the update unit's script and the install docs: no DB,
no network, never skips.

* The lock is pip-compile output for CPython 3.14 with a SHA-256 on every
  pin, CPU torch from PyTorch's CPU index (no CUDA runtime), and it covers
  everything a server runs: the core dependencies, the ``real-clients`` and
  ``voice-profile`` extras, resemblyzer, and the build tools the sdist-only
  pins are built with.
* Its pins satisfy pyproject (a pyproject change without a regenerated lock
  fails here) and stay above the advisory lines.
* ``apply-update.sh`` and the compile script agree on the lock's name and
  extras, the update unit uses the lock only when ``DOMOVOI_USE_LOCK=1``,
  and the server install docs install from it without the ``dev`` extra.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCK = REPO_ROOT / "requirements-linux-py314.lock"
LOCK_IN = REPO_ROOT / "requirements-linux-py314.in"
PYPROJECT = REPO_ROOT / "pyproject.toml"
APPLY_UPDATE = REPO_ROOT / "scripts" / "linux" / "apply-update.sh"
COMPILE = REPO_ROOT / "scripts" / "linux" / "compile-linux-lock.sh"
LINUX_HOST = REPO_ROOT / "docs" / "LINUX_HOST.md"
LOCKED_EXTRAS = ("real-clients", "voice-profile")
CPU_INDEX = "https://download.pytorch.org/whl/cpu"

# Advisory lines the lock must stay above (tooling/pip-audit.md, 2026-10).
ADVISORY_FLOORS = {
    "urllib3": Version("2.8.0"),
    "aiohttp": Version("3.14.3"),
    "anyio": Version("4.14.2"),
    "multidict": Version("6.9.1"),
}

PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==(\S+?)(?:\s*\\)?$")


def _blocks() -> dict[str, tuple[Version, list[str]]]:
    """name -> (pinned version, its hashes)."""
    out: dict[str, tuple[Version, list[str]]] = {}
    current: str | None = None
    for raw in LOCK.read_text(encoding="utf-8").splitlines():
        m = PIN.match(raw)
        if m:
            current = canonicalize_name(m.group(1))
            out[current] = (Version(m.group(2)), [])
            continue
        h = re.match(r"^\s+--hash=sha256:([0-9a-f]{64})\b", raw)
        if h and current:
            out[current][1].append(h.group(1))
            continue
        if not raw.startswith((" ", "\t")):
            current = None
    return out


def _pyproject() -> dict:
    return tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))


def _server_requirements() -> list[Requirement]:
    data = _pyproject()["project"]
    reqs = [Requirement(r) for r in data["dependencies"]]
    for extra in LOCKED_EXTRAS:
        reqs += [Requirement(r) for r in data["optional-dependencies"][extra]]
    return reqs


def test_lock_is_pip_compile_output_for_python_314() -> None:
    text = LOCK.read_text(encoding="utf-8")
    assert "\r" not in text
    # apply-update.sh's lock_usable reads exactly this header line.
    assert re.search(r"^# This file is autogenerated by pip-compile with Python 3\.14$", text, re.M)
    assert "bash scripts/linux/compile-linux-lock.sh" in text
    assert f"--extra-index-url {CPU_INDEX}" in text


def test_every_pin_carries_a_hash() -> None:
    blocks = _blocks()
    assert len(blocks) > 50
    unhashed = sorted(n for n, (_, hashes) in blocks.items() if not hashes)
    assert unhashed == [], f"pins without --hash: {unhashed}"


def test_lock_pins_cpu_torch_and_no_cuda_runtime() -> None:
    blocks = _blocks()
    assert "torch" in blocks
    assert blocks["torch"][0].local == "cpu", f"torch=={blocks['torch'][0]} is not the +cpu build"
    cuda = sorted(n for n in blocks if n.startswith("nvidia-") or n == "triton")
    assert cuda == [], f"CUDA runtime wheels in the CPU lock: {cuda}"


def test_lock_covers_everything_a_server_runs() -> None:
    blocks = _blocks()
    missing = sorted(
        {canonicalize_name(r.name) for r in _server_requirements()} - set(blocks)
    )
    assert missing == [], f"in pyproject (core + {', '.join(LOCKED_EXTRAS)}) but not locked: {missing}"
    # Not in pyproject, but on every server: the speaker encoder, and the
    # build tools the sdist-only pins and `pip install -e .` build with.
    for name in ("resemblyzer", "setuptools", "wheel"):
        assert name in blocks, f"{name} is not in the lock"
    # webrtcvad (under resemblyzer) imports pkg_resources, gone in setuptools 82.
    assert blocks["setuptools"][0] < Version("82")


def test_lock_pins_satisfy_pyproject() -> None:
    blocks = _blocks()
    for req in _server_requirements():
        if req.marker is not None and not req.marker.evaluate({"python_version": "3.14", "sys_platform": "linux"}):
            continue
        version = blocks[canonicalize_name(req.name)][0]
        assert req.specifier.contains(version, prereleases=True), f"{req.name}=={version} does not satisfy {req}"


@pytest.mark.parametrize("package", sorted(ADVISORY_FLOORS))
def test_lock_stays_above_the_advisory_lines(package: str) -> None:
    version = _blocks()[package][0]
    assert version >= ADVISORY_FLOORS[package], f"{package}=={version} is below {ADVISORY_FLOORS[package]}"


def test_update_unit_and_compile_script_agree_on_the_lock() -> None:
    script = APPLY_UPDATE.read_text(encoding="utf-8")
    assert "DEPS_LOCK=${DOMOVOI_DEPS_LOCK-requirements-linux-py314.lock}" in script
    assert f"LOCK_EXTRAS={','.join(LOCKED_EXTRAS)}" in script
    # A server re-sync never installs the test suite's extra by default.
    assert "PIP_EXTRAS=${DOMOVOI_PIP_EXTRAS-real-clients,voice-profile}" in script
    compile_sh = COMPILE.read_text(encoding="utf-8")
    assert f"EXTRAS=({' '.join(LOCKED_EXTRAS)})" in compile_sh
    assert "--generate-hashes" in compile_sh and "--allow-unsafe" in compile_sh
    assert re.search(r"python:3\.14-slim@sha256:[0-9a-f]{64}", compile_sh), "the compile image is not pinned by digest"
    assert "requirements-linux-py314.in" in compile_sh and LOCK_IN.is_file()


def test_an_update_uses_the_lock_only_when_opted_in() -> None:
    # A live box's first update after the lock lands must re-sync the way
    # it always has: the lock moves every package to its own version, and
    # it should first be re-seeded from that box's pip freeze.
    script = APPLY_UPDATE.read_text(encoding="utf-8")
    assert "USE_LOCK=${DOMOVOI_USE_LOCK:-0}" in script
    body = script[script.index("\nsync_deps() {"):]
    body = body[: body.index("\n}\n")]
    assert body.index('if [ "$USE_LOCK" != 1 ]; then') < body.index("lock_usable"), (
        "sync_deps must take the resolver path before it looks at the lock"
    )
    doc = LINUX_HOST.read_text(encoding="utf-8")
    assert "### The hash-pinned lock" in doc and "DOMOVOI_USE_LOCK=1" in doc
    assert "DOMOVOI_LOCK_SEED=domovoi-freeze.txt" in doc, "the doc must say to re-seed from the box first"


def test_linux_install_docs_install_from_the_lock() -> None:
    doc = LINUX_HOST.read_text(encoding="utf-8")
    assert "pip install --require-hashes -c requirements-linux-py314.lock setuptools wheel" in doc
    assert "pip install --require-hashes --no-build-isolation -r requirements-linux-py314.lock" in doc
    assert "pip install --no-deps --no-build-isolation -e ." in doc


@pytest.mark.parametrize("doc", ["docs/LINUX_HOST.md", "README.md", "docs/SETUP_RUNBOOK.md"])
def test_install_paths_drop_the_dev_extra(doc: str) -> None:
    text = (REPO_ROOT / doc).read_text(encoding="utf-8")
    assert not re.search(r"pip install -e \"\.\[dev,", text), f"{doc} still installs the dev extra"
