package com.lazythumblabs.ltl.util;

/**
 * Vectors produced by the Python implementation, checked in as
 * constants.
 *
 * <p>The relay and the Domovoi plugin are two implementations of one
 * protocol written in two languages, and the only thing that keeps them
 * honest is running both against the same bytes. These were generated by
 * {@code plugin-ltl-remote/domovoi_plugin_ltl_remote/crypto.py} and
 * {@code framing.py}; if a change to either side breaks a test that uses
 * them, that is the point.
 *
 * <p>Regenerate with the snippet in
 * {@code ltl/docs/PROTOCOL.md} — never by copying whatever the Java side
 * currently produces, which would make the check circular and worthless.
 */
public final class CrossImplementationVectors {

    private CrossImplementationVectors() {}

    public static final String DH_PUBLIC_KEY =
            "BCoh9_dTf7KpbSsfLgOoO6IQZFTsqUlwCWMnA5CKMqe8dEpPxerpp4NLN70DgrmmzjQdfQ4WfkfyvBCDjH4wYKw";

    public static final String SIG_PUBLIC_KEY =
            "BIIvXfZTqcnCGT9gu9khHmsVRPboRS-buhKZfEMbVZLqCoV8csc8fs56vtXwMQ-ITOJIU_X7HvY2S3SehXLfsLo";

    /** SHA-256("ltl-remote/v1 fp" || dh || sig)[:16], hex, in groups of four. */
    public static final String FINGERPRINT = "B5D9 96A9 FA9A 2BD6 3EE3 8B6F A6C9 8211";

    /** The shorter device form, over the same key. */
    public static final String DEVICE_FINGERPRINT = "8F4F 9791 A987 0ECB";

    /** Bytes 0x00..0x1F, base64url. */
    public static final String CHALLENGE =
            "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8";

    public static final String HOUSEHOLD_UID = "h_0123456789abcdef0123456789abcdef";

    /** ECDSA-P256-SHA256 over (challenge || householdUid), DER, base64url. */
    public static final String CHALLENGE_SIGNATURE =
            "MEYCIQDZSiPpaGfTMoYjRKgyJGRNWux5oHnrXkcwoiBkXwFv5gIhAJz_DltzEKA11lQdBD6R"
                    + "eISXGgXZQ3Odcr5emao9Thx_";

    public static final String PAIRING_CODE = "maple-heron-brick-oak-fern-dawn-owl-river";

    public static final String PAIRING_CODE_HASH =
            "b953d6346e0ce18fd18c4462c146d0d0c14c797d935f094c309a813b0a93b51b";

    /** encode_outer(OP_LINK_DATA, bytes(range(16)), b"sealed") */
    public static final String OUTER_LINK_DATA_HEX =
            "0102000102030405060708090a0b0c0d0e0f7365616c6564";

    /** encode_outer(OP_CONTROL, ZERO_LINK_ID, {"t":"heartbeat"}) */
    public static final String OUTER_CONTROL_HEX =
            "0110000000000000000000000000000000007b2274223a22686561727462656174227d";
}
